kind: pipeline
type: docker
name: build

steps:
  - name: cooked
    image: najahi/oven:proton
    environment:
      BOT_API_KEY:
        from_secret: BOT_API_KEY
      DRONE_SERVER:
          from_secret: DRONE_SERVER
      DRONE_TOKEN:
          from_secret: DRONE_TOKEN
    commands:
      - wget https://raw.githubusercontent.com/Blacksuan19/Scripts/master/dark_ages_ci.sh
      - bash dark_ages_ci.sh phoenix
